[34m[1mwandb[39m[22m: logging graph, to disable use `wandb.watch(log_graph=False)`
[34m[1mwandb[39m[22m: [33mWARNING[39m Serializing object of type list that is 108024 bytes
[34m[1mwandb[39m[22m: [33mWARNING[39m Serializing object of type list that is 121432 bytes
Traceback (most recent call last):
  File "/home/tilingl/ehrgraphs/ehrgraphs/scripts/train_recordgraphs.py", line 134, in <module>
    main()
  File "/home/tilingl/ehrgraphs/ehrgraphs/scripts/train_recordgraphs.py", line 114, in main
    trainer = Trainer(
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1539, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/utilities/device_parser.py", line 151, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []
Traceback (most recent call last):
  File "/home/tilingl/ehrgraphs/ehrgraphs/scripts/train_recordgraphs.py", line 134, in <module>
    main()
  File "/home/tilingl/ehrgraphs/ehrgraphs/scripts/train_recordgraphs.py", line 114, in main
    trainer = Trainer(
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1539, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/tilingl/miniconda3/envs/ehrgraphs2/lib/python3.9/site-packages/pytorch_lightning/utilities/device_parser.py", line 151, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []